#define PROBE_IO_READ_ENTRY(fd,size) PROBE_INT_LONG_ENTRY(IO_READ,fd,size)
#define PROBE_IO_READ_RETURN(fd,size) PROBE_INT_LONG_RETURN(IO_READ,fd,size)
#define PROBE_IO_WRITE_ENTRY(fd,size) PROBE_INT_LONG_ENTRY(IO_WRITE,fd,size)
#define PROBE_IO_WRITE_RETURN(fd,size) PROBE_INT_LONG_RETURN(IO_WRITE,fd,size)