#define PROBE_STRING_ENTRY(PROBE,str) do {\
  if (RUBY_STR_##PROBE##_ENTRY_ENABLED())\
   RUBY_STR_##PROBE##_ENTRY((char*)RSTRING_PTR(str));\
} while (0)
#define PROBE_STRING_INT_ENTRY(PROBE,str,len) do {\
  if (RUBY_STR_##PROBE##_ENTRY_ENABLED())\
   RUBY_STR_##PROBE##_ENTRY((char*)RSTRING_PTR(str),len);\
} while (0)
#define PROBE_STRING1_ENTRY(PROBE,str,str2) do {\
  if (RUBY_STR_##PROBE##_ENTRY_ENABLED())\
   RUBY_STR_##PROBE##_ENTRY((char*)RSTRING_PTR(str),(char*)RSTRING_PTR(str2));\
} while (0)
#define PROBE_STRING_RETURN(PROBE,str) do {\
  if (RUBY_STR_##PROBE##_RETURN_ENABLED())\
   RUBY_STR_##PROBE##_RETURN((char*)RSTRING_PTR(str));\
} while (0)
#define PROBE_STRING_INT_RETURN(PROBE,str,len) do {\
  if (RUBY_STR_##PROBE##_RETURN_ENABLED())\
   RUBY_STR_##PROBE##_RETURN((char*)RSTRING_PTR(str),len);\
} while (0)
#define PROBE_STRING1_RETURN(PROBE,str,str2) do {\
  if (RUBY_STR_##PROBE##_RETURN_ENABLED())\
   RUBY_STR_##PROBE##_RETURN((char*)RSTRING_PTR(str),(char*)RSTRING_PTR(str2));\
} while (0)

#define PROBE_STR_NEW_ENTRY(ptr,len) PROBE_STR_INT_ENTRY(STR_NEW,ptr,len)
#define PROBE_STR_NEW_RETURN(ptr,len) PROBE_STR_INT_RETURN(STR_NEW,ptr,len)
#define PROBE_STR_NEW_SHARED_ENTRY(str) PROBE_STRING_ENTRY(NEW_SHARED,str)
#define PROBE_STR_NEW_SHARED_RETURN(str) PROBE_STRING_RETURN(NEW_SHARED,str)
#define PROBE_STR_FREE_ENTRY(str) PROBE_STRING_ENTRY(FREE,str)
#define PROBE_STR_FREE_RETURN(str) PROBE_STRING_RETURN(FREE,str)
#define PROBE_STR_DUP_ENTRY(str) PROBE_STRING_ENTRY(DUP,str)
#define PROBE_STR_DUP_RETURN(str) PROBE_STRING_RETURN(DUP,str)
#define PROBE_STR_REPLACE_ENTRY(str,str2) PROBE_STRING1_ENTRY(REPLACE,str,str2)
#define PROBE_STR_REPLACE_RETURN(str,str2) PROBE_STRING1_RETURN(REPLACE,str,str2)
#define PROBE_STR_SHARED_REPLACE_ENTRY(str,str2) PROBE_STRING1_ENTRY(SHARED_REPLACE,str,str2)
#define PROBE_STR_SHARED_REPLACE_RETURN(str,str2) PROBE_STRING1_RETURN(SHARED_REPLACE,str,str2)
#define PROBE_STR_BUF_NEW_ENTRY(size) PROBE_INT_ENTRY(STR_BUF_NEW,size)
#define PROBE_STR_BUF_NEW_RETURN(size) PROBE_INT_RETURN(STR_BUF_NEW,size)
#define PROBE_STR_BUF_CSTR_NEW_ENTRY(ptr) PROBE_STR_ENTRY(STR_BUF_CSTR_NEW,ptr)
#define PROBE_STR_BUF_CSTR_NEW_RETURN(ptr) PROBE_STR_RETURN(STR_BUF_CSTR_NEW,ptr)
#define PROBE_STR_RESIZE_CAPACITY_ENTRY(str,cap) PROBE_STRING_INT_ENTRY(RESIZE_CAPACITY,str,cap)
#define PROBE_STR_RESIZE_CAPACITY_RETURN(str,cap) PROBE_STRING_INT_RETURN(RESIZE_CAPACITY,str,cap)
#define PROBE_STR_DEC_LENGTH_ENTRY(str) PROBE_STRING_ENTRY(DEC_LENGTH,str)
#define PROBE_STR_DEC_LENGTH_RETURN(str) PROBE_STRING_RETURN(DEC_LENGTH,str)
#define PROBE_STR_SET_LENGTH_ENTRY(str,len) PROBE_STRING_INT_ENTRY(SET_LENGTH,str,len)
#define PROBE_STR_SET_LENGTH_RETURN(str,len) PROBE_STRING_INT_RETURN(SET_LENGTH,str,len)